version: "3.8"
services:
  pilecco_xml_sync:
    image: ghcr.io/joaovnery/xml_sync:latest
    container_name: xml_sync_container
    restart: unless-stopped
    environment:
      - .env
    ports:
      - "${PORT:-3333}:${PORT:-3333}"
    volumes:
      - ./xmls_coletados:/app/xmls_coletados
      - ./data:/app/data
