export const envConfig = {
  PORT: process.env.PORT,
  EMAIL_APP_PASSWORD: process.env.EMAIL_APP_PASSWORD,
  EMAIL_USER: process.env.EMAIL_USER,
  EMAIL_SENDER: process.env.EMAIL_SENDER,
  EMAIL_RECIPIENT: process.env.EMAIL_RECIPIENT,
  EMAIL_CC: process.env.EMAIL_CC,
  GOOGLE_CHAT_WEBHOOK_URL: process.env.GOOGLE_CHAT_WEBHOOK_URL,
  CRON_SCHEDULE: process.env.CRON_SCHEDULE,
  USE_FIX_DATE: process.env.USE_FIX_DATE,
  INI_DATE: process.env.INI_DATE,
  END_DATE: process.env.END_DATE,
  LOOKBACKDAYS: process.env.LOOKBACKDAYS,
  CLIENT_NAME: process.env.CLIENT_NAME,
  DB_HOST: process.env.DB_HOST,
  DB_PORT: process.env.DB_PORT,
  DB_USER: process.env.DB_USER,
  DB_PASSWORD: process.env.DB_PASSWORD,
  DB_NAME: process.env.DB_NAME,
};
